# This playbook will create an ansible sudo user on the remote host to run commands without password with ssh key.
# Modify service_user and ssh_public_key_file vars according to your env.
---
- vars_prompt:
  - name: 'target_hosts'
    prompt: "Enter target host or group"
    private: no
  hosts: '{{ target_hosts}}'
  sudo: yes
  vars: 
    service_user: ansible_kha
    ssh_public_key_file: /root/.ssh/id_rsa.pub 

  tasks:
  - name: create ansible user
    user: name={{ service_user }} shell=/bin/bash 

  - name: Install the libselinux-python package
    yum: name=libselinux-python state=installed
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version in ['6', '7']

  - name: deploy ssh pub key
    authorized_key: user={{ service_user }} key="{{ lookup('file', ssh_public_key_file) }}"

  - name: passwordless sudo
    lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^{{ service_user }} '
        line: '{{ service_user }}  ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
