---
- vars_prompt:
  - name: 'target_hosts'
    prompt: "Enter target host or group"
    private: no
  hosts: '{{ target_hosts}}'
  become: yes

  tasks:

  - block:
    - name: install ntp ubuntu 
      apt: name={{ item }} state=latest
      with_items:
      - ntp
      - tzdata

    - name: enable ntp
      service: name=ntp enabled=yes state=started

    when: ansible_distribution in ['Ubuntu', 'Debian']


  - block:
    - name: instal ntp centos
      yum: name={{ item }}  state=latest
      with_items:
      - ntp
      - tzdata

    - name: enable ntpd
      service: name=ntpd enabled=yes state=started

    when: ansible_distribution == 'CentOS'


  - name: set correct timezone
    shell: timedatectl set-timezone Europe/Moscow
    ignore_errors: yes


  - block:
    - name: remove localtime 
      file: path=/etc/localtime state=absent

    - name: set timezone centos6
      file: src=/usr/share/zoneinfo/Europe/Moscow dest=/etc/localtime state=link

    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

